

# This file was *autogenerated* from the file rogue.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0x1a0111ea397fe69a4b1ba7b6434bacd764774b84f38512bf6730d2a0f6b0f6241eabfffeb153ffffb9feffffffffaaab = Integer(0x1a0111ea397fe69a4b1ba7b6434bacd764774b84f38512bf6730d2a0f6b0f6241eabfffeb153ffffb9feffffffffaaab); _sage_const_12 = Integer(12); _sage_const_0 = Integer(0); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_4 = Integer(4); _sage_const_3 = Integer(3)
import sys
from sage.all import *
proof.all(False)

# Params
p = _sage_const_0x1a0111ea397fe69a4b1ba7b6434bacd764774b84f38512bf6730d2a0f6b0f6241eabfffeb153ffffb9feffffffffaaab 
Fp = GF(p)
F12 = GF(p**_sage_const_12 , name='a'); a = F12.gens()[_sage_const_0 ]
RF = PolynomialRing(F12, name='T'); T = RF.gens()[_sage_const_0 ]
j = (T**_sage_const_2  + _sage_const_1 ).roots(ring=RF, multiplicities=_sage_const_0 )[_sage_const_0 ]
E2 = EllipticCurve(F12, [_sage_const_0 , _sage_const_4 *(j+_sage_const_1 )])

# Nhận input từ tham số dòng lệnh
alice = eval(sys.argv[_sage_const_1 ])
bob = eval(sys.argv[_sage_const_2 ])
charlie = eval(sys.argv[_sage_const_3 ])

def get_pt(c):
    x = sum([Fp(k) * a**i for i, k in enumerate(c)])
    return E2.lift_x(x)

# Tính
P_New = get_pt(charlie) - get_pt(alice) - get_pt(bob)

# In output format X|Y
lx = P_New[_sage_const_0 ].list(); ly = P_New[_sage_const_1 ].list()
while len(lx)<_sage_const_12 : lx.append(_sage_const_0 )
while len(ly)<_sage_const_12 : ly.append(_sage_const_0 )
print(f"{str(lx)[_sage_const_1 :-_sage_const_1 ]}|{str(ly)[_sage_const_1 :-_sage_const_1 ]}")

