import os

from Crypto.Cipher import AES
from Crypto.Util.Padding import pad, unpad
from flask import Flask, jsonify, render_template, request

app = Flask(__name__, static_folder="static", template_folder="templates")

secret_key = open("./secret/key", "rb").read()

flag = open("./secret/flag", "r").read()

generated_trialkeys = {}


@app.route("/")
def index():
    return render_template("index.html")


@app.route("/api/check/<key>")
def key_check(key):
    iv, ciphertext = bytes.fromhex(key)[:16], bytes.fromhex(key)[16:]
    cipher = AES.new(key=secret_key, mode=AES.MODE_CBC, iv=iv)
    req_ip = request.remote_addr
    try:
        plaintext_bytes = unpad(cipher.decrypt(ciphertext), cipher.block_size)
        plaintext = plaintext_bytes.decode("latin1")
    except ValueError as e:
        return jsonify({"ok": False, "error": str(e)})
    if (
        req_ip in generated_trialkeys
        and plaintext_bytes.hex() == generated_trialkeys[req_ip]
    ):
        return jsonify(
            {"ok": True, "valid": False, "message": "key valid for " + req_ip}
        )
    elif not req_ip in generated_trialkeys:
        return jsonify(
            {
                "ok": True,
                "valid": False,
                "message": "You have not generated a key yet. Keys generated by others will not work for security purposes",
            }
        )
    elif plaintext == "v@l1d_adm1n_k3y_thatimadesure_is2blocks+long_:)":
        return jsonify(
            {
                "ok": True,
                "valid": True,
                "message": f"Valid admin product key. Here is your flag: {flag}",
            }
        )
    else:
        return jsonify(
            {
                "ok": True,
                "valid": False,
                "message": f'Invalid/expired key for user "{plaintext.split(" ")[0]}". Please generate a new one',
            }
        )


@app.route("/api/generate_key")
def key_generate():
    cipher = AES.new(key=secret_key, mode=AES.MODE_CBC)

    user_ip = request.remote_addr

    random_activationKey = str.encode(user_ip) + b" " + bytearray(os.urandom(1024))
    # 1024 byte++ activation key. Surely that's secure enough?

    encrypted_key = cipher.encrypt(pad(random_activationKey, cipher.block_size))

    ciphertext = cipher.iv + encrypted_key

    hex_key = ciphertext.hex()

    generated_trialkeys[user_ip] = random_activationKey.hex()

    return jsonify({"ok": True, "key": hex_key})


@app.route("/api/ping", methods=["GET"])
def ping():
    return jsonify({"pong": True})


if __name__ == "__main__":
    app.run(debug=False, host="0.0.0.0", port=5000)
